export default {
    products:[{
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirt',
        image: '/images/d1.jpg',
        price: 1400,
        brand: 'nike',
        rating: 4,
        numReviews: 10,
        countInStock: 8,
    },
    {
        _id: '2',
        name: 'Cotton Shirt',
        category: 'Shirt',
        image: '/images/d1.jpg',
        price: 1200,
        brand: 'nike',
        rating: 4,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '3',
        name: 'Fit Shirt',
        category: 'Shirt',
        image: '/images/d1.jpg',
        price: 1800,
        brand: 'nike',
        rating: 4,
        numReviews: 10, 
        countInStock: 4,
    },
]
}